language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-atomapp' ]; then cd .. && eval "mv $currentfolder generator-atomapp" && cd generator-atomapp; fi

